name: Release

on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - name: Package
      id: package
      run: echo "##[set-output name=filename;]$(npm pack --silent)"
    - name: Verify
      id: verify
      if: success()
      uses: andstor/file-existence-action@v1
      with:
        files: ${{ steps.package.outputs.filename }}
    - name: Upload
      if: steps.verify.outputs.files_exists == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.package.outputs.filename }}
        asset_name: ${{ steps.package.outputs.filename }}
        asset_content_type: binary/octet-stream
    - name: Deploy to NPM
      if: success()
      run: npm publish $PACKAGE_FILE --access public
      env:
        PACKAGE_FILE: ${{ steps.package.outputs.filename }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
